// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: svr/ctx/v1/ctx.proto

package ctxv1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// BaseResponse 基础响应
type BaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 响应码
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`   // 附带消息
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // json数据
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svr_ctx_v1_ctx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svr_ctx_v1_ctx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_svr_ctx_v1_ctx_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BaseResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// CtxUserInfo 用户上下文信息
type CtxUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"` // 用户名
	ApiUrl   string `protobuf:"bytes,2,opt,name=apiUrl,proto3" json:"apiUrl,omitempty"`     // 请求地址
}

func (x *CtxUserInfo) Reset() {
	*x = CtxUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svr_ctx_v1_ctx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtxUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtxUserInfo) ProtoMessage() {}

func (x *CtxUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_svr_ctx_v1_ctx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtxUserInfo.ProtoReflect.Descriptor instead.
func (*CtxUserInfo) Descriptor() ([]byte, []int) {
	return file_svr_ctx_v1_ctx_proto_rawDescGZIP(), []int{1}
}

func (x *CtxUserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CtxUserInfo) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

// ListPageReq 列表分页读取
type ListPageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // 页数，默认1, 传-1表示不分页，默认20
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 页展示个数，默认20
}

func (x *ListPageReq) Reset() {
	*x = ListPageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svr_ctx_v1_ctx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPageReq) ProtoMessage() {}

func (x *ListPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_svr_ctx_v1_ctx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPageReq.ProtoReflect.Descriptor instead.
func (*ListPageReq) Descriptor() ([]byte, []int) {
	return file_svr_ctx_v1_ctx_proto_rawDescGZIP(), []int{2}
}

func (x *ListPageReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPageReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_svr_ctx_v1_ctx_proto protoreflect.FileDescriptor

var file_svr_ctx_v1_ctx_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x76, 0x72, 0x2f, 0x63, 0x74, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x74, 0x78,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x76, 0x72, 0x2e, 0x63, 0x74, 0x78, 0x2e,
	0x76, 0x31, 0x22, 0x48, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x0b,
	0x43, 0x74, 0x78, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x55, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x55, 0x72, 0x6c, 0x22,
	0x37, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x4d, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e,
	0x6e, 0x6e, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x42, 0x03, 0x43, 0x74, 0x78, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x59, 0x65, 0x52, 0x75, 0x79, 0x69, 0x2f, 0x64, 0x66, 0x73, 0x2d, 0x67, 0x6f,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x76, 0x72, 0x2f, 0x63, 0x74, 0x78, 0x2f, 0x76,
	0x31, 0x3b, 0x63, 0x74, 0x78, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svr_ctx_v1_ctx_proto_rawDescOnce sync.Once
	file_svr_ctx_v1_ctx_proto_rawDescData = file_svr_ctx_v1_ctx_proto_rawDesc
)

func file_svr_ctx_v1_ctx_proto_rawDescGZIP() []byte {
	file_svr_ctx_v1_ctx_proto_rawDescOnce.Do(func() {
		file_svr_ctx_v1_ctx_proto_rawDescData = protoimpl.X.CompressGZIP(file_svr_ctx_v1_ctx_proto_rawDescData)
	})
	return file_svr_ctx_v1_ctx_proto_rawDescData
}

var file_svr_ctx_v1_ctx_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_svr_ctx_v1_ctx_proto_goTypes = []interface{}{
	(*BaseResponse)(nil), // 0: svr.ctx.v1.BaseResponse
	(*CtxUserInfo)(nil),  // 1: svr.ctx.v1.CtxUserInfo
	(*ListPageReq)(nil),  // 2: svr.ctx.v1.ListPageReq
}
var file_svr_ctx_v1_ctx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svr_ctx_v1_ctx_proto_init() }
func file_svr_ctx_v1_ctx_proto_init() {
	if File_svr_ctx_v1_ctx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svr_ctx_v1_ctx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svr_ctx_v1_ctx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtxUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svr_ctx_v1_ctx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svr_ctx_v1_ctx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svr_ctx_v1_ctx_proto_goTypes,
		DependencyIndexes: file_svr_ctx_v1_ctx_proto_depIdxs,
		MessageInfos:      file_svr_ctx_v1_ctx_proto_msgTypes,
	}.Build()
	File_svr_ctx_v1_ctx_proto = out.File
	file_svr_ctx_v1_ctx_proto_rawDesc = nil
	file_svr_ctx_v1_ctx_proto_goTypes = nil
	file_svr_ctx_v1_ctx_proto_depIdxs = nil
}
